#!/usr/bin/python

print('Set variables.')
host_name = 'oracle.internal.com'
admin_user = 'weblogic'
admin_password = 'weblogic1'
admin_port = '7001'
mw_home = '/u01/app/oracle/middleware'
domain_name = 'WlsDomain'
domain_home = mw_home + '/user_projects/domains/' + domain_name   # Check path is correct.
wl_home = mw_home + '/wlserver_10.3'
db_url = 'jdbc:oracle:thin:@oracle.internal.com:1521/ORA11G.oracle.com'
db_user = 'sys'   
db_password = 'oracle'
data_source_user_prefix= 'wls11g'
data_source_test='SQL SELECT 1 FROM DUAL';


print('Create domain (' + domain_name + ').')
print('Load templates.')
readTemplate(wl_home + '/common/templates/domains/wls.jar')

#addTemplate(mw_home + '/oracle_common/common/templates/applications/jrf_template_11.1.1.jar')
#addTemplate(mw_home + '/oracle_common/common/templates/applications/oracle.em_11_1_1_0_0_template.jar')


print('AdminServer settings.')
cd('/Security/base_domain/User/' + admin_user)
cmo.setPassword(admin_password)
cd('/Server/AdminServer')
cmo.setName('AdminServer')
cmo.setListenPort(int(admin_port))
cmo.setListenAddress(host_name)

jdbcsystemresources = cmo.getJDBCSystemResources();
for jdbcsystemresource in jdbcsystemresources:
    cd ('/JDBCSystemResource/' + jdbcsystemresource.getName() + '/JdbcResource/' + jdbcsystemresource.getName() + '/JDBCConnectionPoolParams/NO_NAME_0');
    cmo.setInitialCapacity(1);
    cmo.setMaxCapacity(15);
    cmo.setMinCapacity(1);
    cmo.setStatementCacheSize(0);
    cmo.setTestConnectionsOnReserve(java.lang.Boolean('false'));
    cmo.setTestTableName(data_source_test);
    cmo.setConnectionCreationRetryFrequencySeconds(30);
    cd ('/JDBCSystemResource/' + jdbcsystemresource.getName() + '/JdbcResource/' + jdbcsystemresource.getName() + '/JDBCDriverParams/NO_NAME_0');
    cmo.setUrl(db_url);
    cmo.setPasswordEncrypted(db_password);
   
    cd ('/JDBCSystemResource/' + jdbcsystemresource.getName() + '/JdbcResource/' + jdbcsystemresource.getName() + '/JDBCDriverParams/NO_NAME_0/Properties/NO_NAME_0/Property/user');
    cmo.setValue(cmo.getValue().replace('DEV',data_source_user_prefix));
    cd('/');


#getDatabaseDefaults()

print('Run in production mode.')
setOption('ServerStartMode','prod')

print('Write the domain and close the template.')
setOption('OverwriteDomain', 'true')
writeDomain(domain_home)
closeTemplate()

exit()